//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientOld
    {
        public ClientOld()
        {
            this.Screening = new HashSet<Screening>();
        }
    
        public string ClientID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string IDNumber { get; set; }
        public string Gender { get; set; }
        public Nullable<bool> isHeadOfHousehold { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<bool> isAttendingSchool { get; set; }
        public string Grade { get; set; }
        public Nullable<int> NameOfSchool { get; set; }
        public Nullable<System.DateTime> LastSyncDateFromServer { get; set; }
        public Nullable<System.DateTime> LastSyncDateToServer { get; set; }
        public Nullable<System.DateTime> LastDateUpdated { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        public virtual ICollection<Screening> Screening { get; set; }
    }
}
