//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int UserID { get; set; }
        public string HeadOfHousehold { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string GPSLatitude { get; set; }
        public string GPSLongitude { get; set; }
        public string IDNo { get; set; }
        public string ClinicUsed { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Gender { get; set; }
        public string AttendingSchool { get; set; }
        public string Grade { get; set; }
        public string NameofSchool { get; set; }
    }
}
