//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class impiloEntities : DbContext
    {
        public impiloEntities()
            : base("name=impiloEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BloodSuger> BloodSuger { get; set; }
        public virtual DbSet<BPReading> BPReading { get; set; }
        public virtual DbSet<ChildHealth> ChildHealth { get; set; }
        public virtual DbSet<ClientOld> ClientOld { get; set; }
        public virtual DbSet<Clinic> Clinic { get; set; }
        public virtual DbSet<CurrentMedications> CurrentMedications { get; set; }
        public virtual DbSet<Diabetes> Diabetes { get; set; }
        public virtual DbSet<Disease> Disease { get; set; }
        public virtual DbSet<ElderlyCareAssessment> ElderlyCareAssessment { get; set; }
        public virtual DbSet<Environmental> Environmental { get; set; }
        public virtual DbSet<EnvironmentalExtra> EnvironmentalExtra { get; set; }
        public virtual DbSet<Epilepsy> Epilepsy { get; set; }
        public virtual DbSet<General> General { get; set; }
        public virtual DbSet<HIV> HIV { get; set; }
        public virtual DbSet<HIV_Tab> HIV_Tab { get; set; }
        public virtual DbSet<Hut> Hut { get; set; }
        public virtual DbSet<Hypertension> Hypertension { get; set; }
        public virtual DbSet<Medication> Medication { get; set; }
        public virtual DbSet<MentalHealth> MentalHealth { get; set; }
        public virtual DbSet<Other_Tab> Other_Tab { get; set; }
        public virtual DbSet<OtherCondition> OtherCondition { get; set; }
        public virtual DbSet<Pregnancy> Pregnancy { get; set; }
        public virtual DbSet<Screening> Screening { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TBContactTracing> TBContactTracing { get; set; }
        public virtual DbSet<Tubercolosis> Tubercolosis { get; set; }
        public virtual DbSet<Chow> Chow { get; set; }
        public virtual DbSet<Client> Client { get; set; }
    }
}
