//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diabetes
    {
        public string ScreeningID { get; set; }
        public string YearOfDiagonosis { get; set; }
        public Nullable<bool> regularlyThirsty { get; set; }
        public Nullable<bool> WeightLoss { get; set; }
        public Nullable<bool> BlurredVision { get; set; }
        public Nullable<bool> UrinatingMore { get; set; }
        public Nullable<bool> NauseaOrVomitting { get; set; }
        public string FootExamResult { get; set; }
        public Nullable<bool> ReferralToClinic { get; set; }
        public string ReferralNo { get; set; }
        public Nullable<bool> FamilyMemberWith { get; set; }
    
        public virtual Screening Screening { get; set; }
    }
}
