//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Screening
    {
        public Screening()
        {
            this.CurrentMedications = new HashSet<CurrentMedications>();
            this.Other_Tab = new HashSet<Other_Tab>();
        }
    
        public string ScreeningID { get; set; }
        public Nullable<System.DateTime> ScreeningDate { get; set; }
        public string ClientId { get; set; }
    
        public virtual ClientOld ClientOld { get; set; }
        public virtual ICollection<CurrentMedications> CurrentMedications { get; set; }
        public virtual Diabetes Diabetes { get; set; }
        public virtual HIV HIV { get; set; }
        public virtual HIV_Tab HIV_Tab { get; set; }
        public virtual Hypertension Hypertension { get; set; }
        public virtual MentalHealth MentalHealth { get; set; }
        public virtual ICollection<Other_Tab> Other_Tab { get; set; }
        public virtual OtherCondition OtherCondition { get; set; }
        public virtual Pregnancy Pregnancy { get; set; }
        public virtual Tubercolosis Tubercolosis { get; set; }
    }
}
